services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: finnensley
      POSTGRES_PASSWORD: Finnigan2025
      POSTGRES_DB: shipping_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
